prometheus:
  secretsName: "prod/publicai/prometheus/secrets"

grafana:
  secretsName: "prod/publicai/grafana/secrets"

argocdNotifications:
  enabled: true
  secretsName: "prod/publicai/argocd/notifications"

healthcheck:
  enabled: true

awsRegion: "eu-central-2"

