apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.searxng.name }}-config
  namespace: {{ .Values.namespace }}
data:
  settings.yml: |
    # Minimal SearXNG configuration for OpenWebUI
    use_default_settings: true
    
    general:
      instance_name: "SearXNG"
      
    server:
      secret_key: "{{ .Values.searxng.secretKey | default "change-this-secret-key-in-production" }}"
      port: 8080
      bind_address: "0.0.0.0"
      limiter: false
      image_proxy: false
      
    # valkey:
    #   url: "${REDIS_URL}"
      
    search:
      safe_search: 0
      formats:
        - html
        - json  # Required for OpenWebUI integration
        
    engines:
      # Fast, reliable engines only
      - name: google
        engine: google
        shortcut: go
        
      - name: duckduckgo
        engine: duckduckgo
        shortcut: ddg
        
      - name: bing
        engine: bing
        shortcut: bi
        
      # Disable slower engines
      - name: startpage
        disabled: true
        
      - name: yahoo
        disabled: true
        
      - name: yandex
        disabled: true
        
      - name: searx
        disabled: true