# models:
# - model_name: allenai/Olmo-3-7B-Instruct
#   litellm_params:
#     model: openai/allenai/Olmo-3-7B-Instruct
#     api_base: https://api-internal-intel.publicai.co/olmo/v1
#     api_key: os.environ/VLLM_API_KEY_INTEL
#     ssl_verify: false
#     weight: 1
#     temperature: 0.6
#     top_p: 0.95
#     max_tokens: 16384
#   model_info:
#     input_cost_per_token: 0.00000010
#     output_cost_per_token: 0.00000020
# fallbacks:
# - swiss-ai/apertus-v1.5-8b