environments:
  - staging
  - prod
models:
- model_name: speakleash/Bielik-11B-v3.0-Instruct
  litellm_params:
    model: openai/speakleash/Bielik-11B-v3.0-Instruct
    api_base: https://llmlab.plgrid.pl/api/v1
    api_key: os.environ/BIELIK_API_KEY
  model_info:
    input_cost_per_token: 0.00000040
    output_cost_per_token: 0.00000040
fallbacks:
- aisingapore/Qwen-SEA-LION-v4-32B-IT
- apertus-v1.5-70b