# Default values for monitoring-resources.
# This is a YAML-formatted file.

prometheus:
  secretsName: ""

grafana:
  secretsName: ""

argocdNotifications:
  enabled: true
  secretsName: "prod/publicai/argocd/notifications"

healthcheck:
  enabled: true

awsRegion: "us-east-1"

