prometheus:
  secretsName: "staging/aichat/prometheus/secrets"

grafana:
  secretsName: "staging/aichat/grafana/secrets"

argocdNotifications:
  enabled: true
  secretsName: "staging/aichat/argocd/notifications"

healthcheck:
  enabled: true

awsRegion: "us-east-1"

