global:
  aws:
    region: us-east-1

litellm:
  secrets:
    manualSecretsName: "staging/aichat/litellm/manual-secrets"
    managedSecretsName: "staging/aichat/open-webui/managed-secrets"
  prometheus:
    enabled: true

lago:
  serviceAccount:
    roleArn: "arn:aws:iam::818561370924:role/Lago-IRSA-Role"
  apiUrl: "https://lago-api.ai-staging.chat"
  frontUrl: "https://lago.ai-staging.chat"
  global:
    existingSecret: lago-db-secrets
    s3:
      enabled: true
      bucket: "staging-aichat-bucket"
      region: "us-east-1"
      endpoint: "https://s3.us-east-1.amazonaws.com"
    smtp:
      enabled: false
      fromEmail: "support@ai-staging.chat"
  api:
    livenessProbe:
      initialDelaySeconds: 90
  worker:
    livenessProbe:
      initialDelaySeconds: 90
  billingWorker:
    livenessProbe:
      initialDelaySeconds: 90
  clockWorker:
    livenessProbe:
      initialDelaySeconds: 90
  eventsWorker:
    livenessProbe:
      initialDelaySeconds: 90
  paymentWorker:
    livenessProbe:
      initialDelaySeconds: 90
  pdfWorker:
    livenessProbe:
      initialDelaySeconds: 90
  webhookWorker:
    livenessProbe:
      initialDelaySeconds: 90
