{
 "title": "Health Check",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1h",
 "panels": [
  { "title": "Model Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Suppliers",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "suppliers_model_test_success != bool 1",
     "legendFormat": "{{model}}"
    }
   ]
  },
  {
   "title": "LiteLLM",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "litellm_router_model_test_success != bool 1",
     "legendFormat": "{{model}}"
    }
   ]
  },
  {
   "title": "Hugging Face Success",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "huggingface_model_test_success != bool 1",
     "legendFormat": "{{model}}"
    }
   ]
  },
  {
   "title": "Zuplo",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "zuplo_model_test_success != bool 1",
     "legendFormat": "{{model}}"
    }
   ]
  },
  { "title": "TTFT", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "LiteLLM TTFT",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "litellm_router_model_ttft_seconds",
     "legendFormat": "{{model}}"
    }
   ]
  },
  {
   "title": "Zuplo TTFT",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "targets": [
    { "expr": "zuplo_model_ttft_seconds", "legendFormat": "{{model}}" }
   ]
  },
  {
   "title": "Suppliers TTFT",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 27 },
   "targets": [
    { "expr": "suppliers_model_ttft_seconds", "legendFormat": "{{model}}" }
   ]
  },
  {
   "title": "Hugging Face TTFT",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 27 },
   "targets": [
    { "expr": "huggingface_model_ttft_seconds", "legendFormat": "{{model}}" }
   ]
  }
 ]
}