# Ingress configuration for web services
domain: publicai.co
certificateArn: ""

ingresses:
  - enabled: true
    name: web-public-ingress
    host: chat.{{ .Values.domain }}
    annotations:
      kubernetes.io/ingress.class: alb-web
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/target-type: ip
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
      alb.ingress.kubernetes.io/ssl-redirect: "443"
      alb.ingress.kubernetes.io/certificate-arn: "{{ .Values.certificateArn }}"
      alb.ingress.kubernetes.io/group.name: public-group
    targetService:
      name: openwebui-service
      port: 8080

  - enabled: true
    name: litellm-public-ingress
    host: api-internal.{{ .Values.domain }}
    annotations:
      kubernetes.io/ingress.class: alb-web
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/target-type: ip
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
      alb.ingress.kubernetes.io/ssl-redirect: "443"
      alb.ingress.kubernetes.io/certificate-arn: "{{ .Values.certificateArn }}"
      alb.ingress.kubernetes.io/group.name: api-group
    targetService:
      name: litellm-service
      port: 4000

  - enabled: true
    name: lago-public-ingress
    host: lago.{{ .Values.domain }}
    annotations:
      kubernetes.io/ingress.class: alb-web
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/target-type: ip
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
      alb.ingress.kubernetes.io/ssl-redirect: "443"
      alb.ingress.kubernetes.io/certificate-arn: "{{ .Values.certificateArn }}"
      alb.ingress.kubernetes.io/group.name: admin-group
    targetService:
      name: web-services-front-svc
      port: 80

  - enabled: true
    name: lago-api-ingress
    host: lago-api.{{ .Values.domain }}
    annotations:
      kubernetes.io/ingress.class: alb-web
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/target-type: ip
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
      alb.ingress.kubernetes.io/ssl-redirect: "443"
      alb.ingress.kubernetes.io/certificate-arn: "{{ .Values.certificateArn }}"
      alb.ingress.kubernetes.io/healthcheck-path: /health
      alb.ingress.kubernetes.io/group.name: api-group
    targetService:
      name: web-services-api-svc
      port: 3000