apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: storage-class
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/forpublicai/chat.publicai.co'
    targetRevision: main
    path: charts/storage-class
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
