app:
  name: litellm
  image:
    repository: ghcr.io/forpublicai/litellm-database
    tag: v1.92.0
    pullPolicy: Always
  replicas: 1
  port: 4000
  resources:
    requests:
      memory: 3Gi
      cpu: 300m
    limits:
      memory: 4Gi
      cpu: 1000m
service:
  name: litellm-service
  type: ClusterIP
  port: 4000
  targetPort: 4000
serviceAccount:
  enabled: true
  name: litellm-sa
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::901779868336:role/AmazonEKS_LiteLLM_Role
config:
  litellm_settings:
    num_retries: 3
    allowed_fails: 1
    cooldown_time: 60
    cache: true
    require_auth_for_metrics_endpoint: false
    cache_params:
      type: redis
      namespace: litellm.caching
      ttl: 600
secrets:
  name: litellm-secrets
  manualSecretsName: ""
  managedSecretsName: ""


# Environment variables
env:
  aws_region: eu-central-1
  litellmRedisPort: '6379'
  litellmRedisNamespace: litellm
router:
  routingStrategy: simple-shuffle
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 75
  targetMemoryUtilizationPercentage: 85
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 100
        periodSeconds: 15
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 10
        periodSeconds: 60
lago:
  enabled: true
  eventCode: public_ai_models
  chargeBy: end_user_id
  apiBase: https://lago-api.publicai.co
prometheus:
  enabled: false
