{{- if .Values.grafana.secretsName }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-admin-credentials
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: grafana-admin-credentials
    creationPolicy: Owner
    template:
      data:
        admin-user: '{{ "{{ .admin_user }}" }}'
        admin-password: '{{ "{{ .admin_password }}" }}'
  data:
    - secretKey: admin_user
      remoteRef:
        key: {{ .Values.grafana.secretsName }}
        property: admin-user
    - secretKey: admin_password
      remoteRef:
        key: {{ .Values.grafana.secretsName }}
        property: admin-password
{{- end }}
