{{- if .Values.healthcheck.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: health-check-service
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
spec:
  selector:
    app: health-check
  ports:
    - protocol: TCP
      port: {{ .Values.healthcheck.port | default 8000 }}
      targetPort: {{ .Values.healthcheck.port | default 8000 }}
      name: http
{{- end }}

