{{- if .Values.healthcheck.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.healthcheck.secrets.name | default "health-check-secrets" }}
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: {{ .Values.healthcheck.secrets.name | default "health-check-secrets" }}
    creationPolicy: Owner
  data: # these are in the litellm key area
    - secretKey: HF_TEST_TOKEN
      remoteRef:
        key: {{ .Values.healthcheck.secrets.manualSecretsName }}
        property: HF_TEST_TOKEN
    - secretKey: ZUPLO_TEST
      remoteRef:
        key: {{ .Values.healthcheck.secrets.manualSecretsName }}
        property: ZUPLO_TEST
    - secretKey: LITELLM_API_KEY
      remoteRef:
        key: {{ .Values.healthcheck.secrets.manualSecretsName }}
        property: LITELLM_MASTER_KEY
{{- end }}
