{{- if .Values.modellist.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.modellist.secrets.name | default "model-list-secrets" }}
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: {{ .Values.modellist.secrets.name | default "model-list-secrets" }}
    creationPolicy: Owner
  data:
    - secretKey: LITELLM_API_KEY
      remoteRef:
        key: {{ .Values.modellist.secrets.manualSecretsName }}
        property: LITELLM_MASTER_KEY
{{- end }}
