environments:
  - staging
  - prod
models:
- model_name: aisingapore/Qwen-SEA-LION-v4-32B-IT
  litellm_params:
    model: openai/aisingapore/Qwen-SEA-LION-v4-32B-IT
    api_base: https://api.sea-lion.ai
    api_key: os.environ/SEALION_API_KEY
    supports_vision: true
  model_info:
    input_cost_per_token: 0.00000025
    output_cost_per_token: 0.00000050
fallbacks:
- swiss-ai/apertus-70b-instruct
- speakleash/Bielik-11B-v3.0-Instruct