# Default values for tika
# This is the base configuration for Apache Tika server

namespace: web-services

tika:
  name: tika
  replicas: 1
  image:
    repository: apache/tika
    tag: latest-full
  port: 9998
  
  service:
    name: tika-service
    port: 9998
    type: ClusterIP
  
  # Java heap size configuration - optimized for autoscaling
  javaOpts: "-Xms512m -Xmx1536m"
  
  resources:
    requests:
      memory: "768Mi"
      cpu: "250m"
    limits:
      memory: "2Gi"
      cpu: "1000m"

# Autoscaling configuration
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 75
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 100
        periodSeconds: 30
    scaleDown:
      stabilizationWindowSeconds: 600
      policies:
      - type: Percent
        value: 25
        periodSeconds: 60