# Default values for tika
# This is the base configuration for Apache Tika server

namespace: web-services

tika:
  name: tika
  replicas: 1
  image:
    repository: apache/tika
    tag: latest-full
  port: 9998
  
  service:
    name: tika-service
    port: 9998
    type: ClusterIP
  
  # Java heap size configuration - minimal default
  javaOpts: "-Xms256m -Xmx512m"
  
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "200m"