services:
  envoy: 
    image: envoyproxy/envoy:v1.35-latest
    container_name: envoy
    expose: 
      - "10000"
    volumes: 
      - ./envoy.yaml:/etc/envoy/envoy.yaml:ro
    restart: unless-stopped
    environment:
      - SEALION_API_KEY=${SEALION_API_KEY}