apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.secrets.name }}
  namespace: {{ .Values.global.namespace | default "web-services" }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-3"
    helm.sh/resource-policy: keep
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: {{ .Values.secrets.name }}
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        database_url: 'postgresql://postgres:{{ "{{ .DB_PASSWORD | urlquery }}" }}@{{ "{{ .DB_HOST }}" }}:5432/litellm?sslmode=require'
        redis_url: '{{ "{{ .REDIS_URL }}" }}'
        redis_host: '{{ "{{ .REDIS_HOST }}" }}'
        litellm_master_key: '{{ "{{ .LITELLM_MASTER_KEY }}" }}'
        litellm_salt_key: '{{ "{{ .LITELLM_SALT_KEY }}" }}'
        vllm_api_key_intel: '{{ "{{ .VLLM_API_KEY_INTEL }}" }}'
        lago_api_key: '{{ "{{ .LAGO_API_KEY }}" }}'
        cscs_api_key: '{{ "{{ .CSCS_API_KEY }}" }}'
        sealion_api_key: '{{ "{{ .SEALION_API_KEY }}" }}'
        bielik_api_key: '{{ "{{ .BIELIK_API_KEY }}" }}'
        infomaniak_api_key: '{{ "{{ .INFOMANIAK_API_KEY }}" }}'
  data:
    - secretKey: DB_PASSWORD
      remoteRef:
        key: {{ .Values.secrets.dbPasswordArn }}
        property: password
    - secretKey: DB_HOST
      remoteRef:
        key: {{ .Values.secrets.managedSecretsName }}
        property: DB_HOST
    - secretKey: REDIS_URL
      remoteRef:
        key: {{ .Values.secrets.managedSecretsName }}
        property: REDIS_URL
    - secretKey: REDIS_HOST
      remoteRef:
        key: {{ .Values.secrets.managedSecretsName }}
        property: REDIS_HOST
    - secretKey: LITELLM_MASTER_KEY
      remoteRef:
        key: {{ .Values.secrets.manualSecretsName }}
        property: LITELLM_MASTER_KEY
    - secretKey: LITELLM_SALT_KEY
      remoteRef:
        key: {{ .Values.secrets.manualSecretsName }}
        property: LITELLM_SALT_KEY
    - secretKey: VLLM_API_KEY_INTEL
      remoteRef:
        key: {{ .Values.secrets.manualSecretsName }}
        property: VLLM_API_KEY_INTEL
    - secretKey: LAGO_API_KEY
      remoteRef:
        key: {{ .Values.secrets.manualSecretsName }}
        property: LAGO_API_KEY
    - secretKey: CSCS_API_KEY
      remoteRef:
        key: {{ .Values.secrets.manualSecretsName }}
        property: CSCS_API_KEY
    - secretKey: SEALION_API_KEY
      remoteRef:
        key: {{ .Values.secrets.manualSecretsName }}
        property: SEALION_API_KEY
        optional: true
    - secretKey: BIELIK_API_KEY
      remoteRef:
        key: {{ .Values.secrets.manualSecretsName }}
        property: BIELIK_API_KEY
    - secretKey: INFOMANIAK_API_KEY
      remoteRef:
        key: {{ .Values.secrets.manualSecretsName }}
        property: INFOMANIAK_API_KEY


