apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin-credentials
  namespace: {{ .Values.global.namespace | default "web-services" }}
type: Opaque
stringData:
  admin-user: {{ .Values.grafana.adminUser | default "admin" | quote }}
  admin-password: {{ .Values.grafana.adminPassword | default "password" | quote }}
