apiVersion: apps/v1
kind: Deployment
metadata:
  name: openwebui-exporter
  namespace: {{ .Values.global.namespace | default "web-services" }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openwebui-exporter
  template:
    metadata:
      labels:
        app: openwebui-exporter
    spec:
      containers:
        - name: exporter
          image: "{{ .Values.openwebuiexporter.image.repository }}:{{ .Values.openwebuiexporter.image.tag | default "latest" }}"
          ports:
            - containerPort: 9090
              name: http-metrics
          resources:
            {{- toYaml .Values.openwebuiexporter.resources | nindent 12 }}
          env:
            - name: OPENWEBUI_BASE_URL
              value: "http://openwebui-service:8080"
            - name: OPENWEBUI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: openwebui-exporter-secrets
                  key: OPENWEBUI_API_KEY
