apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-resources
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: 'https://github.com/forpublicai/chat.publicai.co'
    targetRevision: dev
    path: charts/monitoring-resources
    helm:
      valueFiles:
        - values.yaml
        - ../../argo/environments/staging/monitoring-resources-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
