apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: promtail
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  sources:
    - repoURL: 'https://grafana.github.io/helm-charts'
      chart: promtail
      targetRevision: 6.17.1
      helm:
        valueFiles:
          - $values/argo/environments/staging/promtail-values.yaml
    - repoURL: 'https://github.com/forpublicai/chat.publicai.co'
      targetRevision: dev
      ref: values
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: web-services
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
