apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: simple-pod-staging
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/forpublicai/chat.publicai.co'
    targetRevision: dev
    path: charts/simple-pod
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: experiment
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
