apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.name }}
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  LICENSE_KEY: {{ .Values.secrets.licenseKey | b64enc }}
  WEBUI_SECRET_KEY: {{ .Values.secrets.webuiSecretKey | b64enc }}
  DATABASE_URL: {{ .Values.secrets.databaseUrl | b64enc }}
  REDIS_URL: {{ .Values.secrets.redisUrl | b64enc }}
  {{/* GOOGLE_CLIENT_ID: {{ .Values.secrets.googleClientId | b64enc }} */}}
  {{/* GOOGLE_CLIENT_SECRET: {{ .Values.secrets.googleClientSecret | b64enc }} */}}
  OAUTH_CLIENT_ID: {{ .Values.secrets.oauthClientId | b64enc }}
  OAUTH_CLIENT_SECRET: {{ .Values.secrets.oauthClientSecret | b64enc }}
  OPENID_PROVIDER_URL: {{ .Values.secrets.openidProviderUrl | b64enc }}
  OPENID_REDIRECT_URI: {{ .Values.secrets.openidRedirectUri | b64enc }}