apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.secrets.name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-3"
    helm.sh/resource-policy: keep
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: {{ .Values.secrets.name }}
    creationPolicy: Owner
  data:
    - secretKey: LICENSE_KEY
      remoteRef:
        key: {{ .Values.secrets.manualSecretsName }}
        property: LICENSE_KEY
    - secretKey: WEBUI_SECRET_KEY
      remoteRef:
        key: {{ .Values.secrets.manualSecretsName }}
        property: WEBUI_SECRET_KEY
    - secretKey: DATABASE_URL
      remoteRef:
        key: {{ .Values.secrets.managedSecretsName }}
        property: DATABASE_URL
    - secretKey: databaseUrl
      remoteRef:
        key: {{ .Values.secrets.managedSecretsName }}
        property: DATABASE_URL
    - secretKey: REDIS_URL
      remoteRef:
        key: {{ .Values.secrets.managedSecretsName }}
        property: REDIS_URL
    - secretKey: redisUrl
      remoteRef:
        key: {{ .Values.secrets.managedSecretsName }}
        property: REDIS_URL
    - secretKey: OAUTH_CLIENT_ID
      remoteRef:
        key: {{ .Values.secrets.managedSecretsName }}
        property: OAUTH_CLIENT_ID
    - secretKey: OAUTH_CLIENT_SECRET
      remoteRef:
        key: {{ .Values.secrets.managedSecretsName }}
        property: OAUTH_CLIENT_SECRET
    - secretKey: OPENID_PROVIDER_URL
      remoteRef:
        key: {{ .Values.secrets.managedSecretsName }}
        property: OPENID_PROVIDER_URL
    - secretKey: OPENID_REDIRECT_URI
      remoteRef:
        key: {{ .Values.secrets.managedSecretsName }}
        property: OPENID_REDIRECT_URI