{{- if .Values.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.app.name }}-hpa
  namespace: {{ .Values.global.namespace | default "web-services" }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.app.name }}
  minReplicas: {{ .Values.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.targetMemoryUtilizationPercentage }}
  {{- if .Values.autoscaling.behavior }}
  behavior:
    {{- if .Values.autoscaling.behavior.scaleUp }}
    scaleUp:
      stabilizationWindowSeconds: {{ .Values.autoscaling.behavior.scaleUp.stabilizationWindowSeconds }}
      policies:
      {{- range .Values.autoscaling.behavior.scaleUp.policies }}
      - type: {{ .type }}
        value: {{ .value }}
        periodSeconds: {{ .periodSeconds }}
      {{- end }}
    {{- end }}
    {{- if .Values.autoscaling.behavior.scaleDown }}
    scaleDown:
      stabilizationWindowSeconds: {{ .Values.autoscaling.behavior.scaleDown.stabilizationWindowSeconds }}
      policies:
      {{- range .Values.autoscaling.behavior.scaleDown.policies }}
      - type: {{ .type }}
        value: {{ .value }}
        periodSeconds: {{ .periodSeconds }}
      {{- end }}
    {{- end }}
  {{- end }}
{{- end }}