apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.name }}
  namespace: {{ .Values.global.namespace | default "web-services" }}
type: Opaque
stringData:
  litellm_master_key: {{ .Values.secrets.litellmMasterKey | quote }}
  litellm_salt_key: {{ .Values.secrets.litellmSaltKey | quote }}
  database_url: {{ .Values.secrets.databaseUrl | quote }}
  redis_url: {{ .Values.secrets.redisUrl | quote }}
  redis_host: {{ .Values.secrets.redisHost | quote }}
  redis_port: {{ .Values.secrets.redisPort | quote }}
  redis_password: {{ .Values.secrets.redisPassword | quote }}
  redis_db: {{ .Values.secrets.redisDb | quote }}
  together_api_key: {{ .Values.secrets.togetherApiKey | quote }}
  sealion_api_key: {{ .Values.secrets.sealionApiKey | quote }}
  vllm_api_key: {{ .Values.secrets.vllmApiKey | quote }}
  vllm_api_key_exoscale: {{ .Values.secrets.vllmApiKeyExoscale | quote }}
  vllm_api_key_anu: {{ .Values.secrets.vllmApiKeyAnu | quote }}
  vllm_api_key_cscs: {{ .Values.secrets.vllmApiKeyCscs | quote }}
  vllm_api_key_cudo: {{ .Values.secrets.vllmApiKeyCudo | quote }}
  vllm_api_key_hh: {{ .Values.secrets.vllmApiKeyHh | quote }}
  vllm_api_key_intel: {{ .Values.secrets.vllmApiKeyIntel | quote }}
  cirrascale_api_key: {{ .Values.secrets.cirrascaleApiKey | quote }}
  parascale_api_key: {{ .Values.secrets.parascaleApiKey | quote }}
  lago_api_key: {{ .Values.secrets.lagoApiKey | quote }}
  multiverse_api_key: {{ .Values.secrets.multiverseApiKey | quote }}
  dicta_api_key: {{ .Values.secrets.dictaApiKey | quote }}
  infomaniak_api_key: {{ .Values.secrets.infomaniakApiKey | quote }}
  deepinfra_api_key: {{ .Values.secrets.deepinfraApiKey | quote }}
  phoeniqs_api_key: {{ .Values.secrets.phoeniqsApiKey | quote }}
  bielik_api_key: {{ .Values.secrets.bielikApiKey | quote }}