apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.name }}
  namespace: {{ .Values.global.namespace | default "web-services" }}
type: Opaque
stringData:
  litellm_master_key: {{ .Values.secrets.litellmMasterKey | quote }}
  litellm_salt_key: {{ .Values.secrets.litellmSaltKey | quote }}
  database_url: {{ .Values.secrets.databaseUrl | quote }}
  redis_url: {{ .Values.secrets.redisUrl | quote }}
  redis_host: {{ .Values.secrets.redisHost | quote }}
  redis_port: {{ .Values.secrets.redisPort | quote }}
  redis_password: {{ .Values.secrets.redisPassword | quote }}
  redis_db: {{ .Values.secrets.redisDb | quote }}
  sealion_api_key: {{ .Values.secrets.sealionApiKey | quote }}
  vllm_api_key_intel: {{ .Values.secrets.vllmApiKeyIntel | quote }}
  lago_api_key: {{ .Values.secrets.lagoApiKey | quote }}
  infomaniak_api_key: {{ .Values.secrets.infomaniakApiKey | quote }}
  bielik_api_key: {{ .Values.secrets.bielikApiKey | quote }}
  cscs_api_key: {{ .Values.secrets.cscsApiKey | quote }}
  hf_credits_key: {{ .Values.secrets.hfCreditsKey | quote }}

