environments:
  - staging
  - prod
models:
- model_name: Cohere/rerank-v3.5
  litellm_params:
    model: bedrock/arn:aws:bedrock:eu-central-1::foundation-model/cohere.rerank-v3-5:0
    aws_region_name: eu-central-1
  model_info:
    input_cost_per_token: 0.000001
