{{- range .Values.ingresses }}
{{- if .enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .name }}
  annotations:
{{- range $key, $value := .annotations }}
  {{- if eq $key "alb.ingress.kubernetes.io/certificate-arn" }}
    {{ $key }}: {{ tpl $value $ | quote }}
  {{- else }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
spec:
  ingressClassName: alb-web
  rules:
  {{- if .host }}
  - host: {{ .host }}
    http:
  {{- else }}
  - http:
  {{- end }}
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .targetService.name }}
            port:
              number: {{ .targetService.port }}
{{- end }}
{{- end }}