models:
- model_name: swiss-ai/apertus-8b-instruct
  litellm_params:
    model: openai/swiss-ai/Apertus-8B-Instruct-2509
    api_base: https://api-internal-intel.publicai.co/apertus/v1
    api_key: os.environ/VLLM_API_KEY_INTEL
    ssl_verify: false
    supports_vision: true
    weight: 20
    temperature: 0.8
    top_p: 0.9
    max_tokens: 16384
  model_info:
    input_cost_per_token: 0.00000010
    output_cost_per_token: 0.00000020
#- model_name: swiss-ai/apertus-8b-instruct
#  litellm_params:
#    model: openai/swiss-ai/Apertus-8B-Instruct-2509
#    api_base: https://api.inference.cscs.ch/v1
#    api_key: os.environ/CSCS_API_KEY
#    ssl_verify: false
#    supports_vision: true
#    weight: 20
#    temperature: 0.8
#    top_p: 0.9
#    max_tokens: 16384
#  model_info:
#    input_cost_per_token: 0.00000010
#    output_cost_per_token: 0.0000002
fallbacks:
- aisingapore/Qwen-SEA-LION-v4-32B-IT
